name: gorilla tech
markdown: kramdown
highlighter: pygments
excerpt_separator: <!--more-->
paginate: 3
paginate_path: "blog/page:num"
permalink: /:categories/:title
gems:
  - jekyll-seo-tag
  - jekyll-paginate
