name: gorilla tech
tagline: tech support to your door
markdown: kramdown
highlighter: pygments
excerpt_separator: <!--more-->
paginate: 3
paginate_path: "blog/page:num"
permalink: /:categories/:title
post_dirs: false
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
